/**
 * importOnlineStoreVehicles.js
 * Imports vehicles from onlinestore.vehicles.json into MongoDB
 * Maps the onlinestore schema → Vehicle model schema
 *
 * Usage (from server/ directory):
 *   node importOnlineStoreVehicles.js
 */

import fs from 'fs';
import path from 'path';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Vehicle from './models/Vehicle.js';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error('❌ MONGODB_URI not found in server/.env');
  process.exit(1);
}

// ── Map category from onlinestore format → Vehicle model enum ─────────────────
function mapCategory(raw) {
  const c = (raw || '').toLowerCase();
  if (c === 'bike')   return 'Bike';
  if (c === 'scooty') return 'Scooty';
  if (c === 'car')    return 'Car';
  if (c === 'ev')     return 'EV';
  // fallback guesses
  if (c.includes('scooty') || c.includes('scooter')) return 'Scooty';
  if (c.includes('bike') || c.includes('motorcycle')) return 'Bike';
  if (c.includes('car') || c.includes('suv') || c.includes('sedan')) return 'Car';
  return 'Car';
}

// ── Map status from onlinestore format → Vehicle model enum ───────────────────
function mapStatus(raw) {
  const s = (raw || '').toLowerCase();
  if (s === 'active')      return 'Available';
  if (s === 'inactive')    return 'Inactive';
  if (s === 'maintenance') return 'Maintenance';
  if (s === 'booked')      return 'Booked';
  if (s === 'reserved')    return 'Reserved';
  return 'Available';
}

// ── Map availability string ────────────────────────────────────────────────────
function mapAvailability(status, availability) {
  if (availability === 'available') return { availableForBooking: true, reason: '' };
  if (availability === 'reserved')  return { availableForBooking: false, reason: 'Reserved' };
  if (availability === 'booked')    return { availableForBooking: false, reason: 'Booked' };
  return { availableForBooking: true, reason: '' };
}

// ── Main converter: onlinestore doc → Vehicle model doc ───────────────────────
function convertVehicle(doc) {
  const r12  = doc.rate12hr    || {};
  const rHr  = doc.rateHourly  || {};
  const r24  = doc.rate24hr    || {};

  return {
    // No vehicleId — auto-generated by pre-save hook (VEH-XXXXX)
    name:            doc.name            || 'Unknown Vehicle',
    brand:           doc.companyName     || doc.name?.split(' ')[0] || 'Unknown',
    regNumber:       doc.vehicleNo       || `IMPORT-${doc._id?.$oid?.slice(-6) || Math.random().toString(36).slice(2,8).toUpperCase()}`,
    category:        mapCategory(doc.category),
    fuelType:        doc.type            || 'Petrol',
    seatingCapacity: doc.seatingCapacity || (mapCategory(doc.category) === 'Bike' || mapCategory(doc.category) === 'Scooty' ? 2 : 4),
    color:           doc.color           || 'Standard',
    meterReading:    doc.meterReading    || 0,
    fuelCapacity:    doc.fuelCapacity    || 0,
    mileage:         doc.mileage         || 0,
    description:     doc.description     || '',
    status:          mapStatus(doc.status),

    pricingPlans: {
      hourly: {
        rate:             rHr.ratePerHour       || 0,
        freeKm:           rHr.kmFreePerHour     || 0,
        fuelChargePerKm:  rHr.fuelChargesperkm  || 0,
        extraKmCharge:    rHr.extraChargePerKm  || 0,
        withFuel:         rHr.withFuelPerHour   || 0,
        withoutFuel:      rHr.withoutFuelPerHour|| 0,
      },
      twelveHour: {
        baseRate:         r12.baseRate           || 0,
        ratePerHour:      r12.ratePerHour        || 0,
        kmLimit:          r12.kmLimit            || 0,
        fuelChargePerKm:  r12.fuelChargesperkm   || 0,
        extraKmCharge:    r12.extraChargePerKm   || 0,
        extraHourCharge:  r12.extraChargePerHour || 0,
        gracePeriod:      r12.gracePeriodMinutes || 0,
        withFuel:         r12.withFuelPerHour    || 0,
        withoutFuel:      r12.withoutFuelPerHour || 0,
      },
      twentyFourHour: {
        baseRate:         r24.baseRate           || 0,
        ratePerHour:      r24.ratePerHour        || 0,
        kmLimit:          r24.kmLimit            || 0,
        fuelChargePerKm:  r24.fuelChargesperkm   || 0,
        extraKmCharge:    r24.extraChargePerKm   || 0,
        extraHourCharge:  r24.extraChargePerHour || 0,
        gracePeriod:      r24.gracePeriodMinutes || 0,
        withFuel:         r24.withFuelPerHour    || 0,
        withoutFuel:      r24.withoutFuelPerHour || 0,
      },
      weekly:  { baseRate: 0, kmLimit: 0, extraKmCharge: 0, extraDayCharge: 0, gracePeriod: 0 },
      monthly: { baseRate: 0, kmLimit: 0, extraKmCharge: 0, extraDayCharge: 0 },
    },

    depositSettings: {
      requireDeposit: doc.requiresDeposit || false,
      amount:         doc.depositAmount   || 0,
    },
    paymentSettings: {
      advanceRequired: doc.requiredPaymentPercentage > 0,
      percentage:      doc.requiredPaymentPercentage || 50,
      acceptedModes:   ['Cash', 'UPI'],
    },
    bookingConfig: {
      bufferTime:      doc.minBufferTime  || 30,
      minBookingHours: 0,
      status:          doc.status === 'active' ? 'Active' : 'Inactive',
      bookingEnabled:  doc.status === 'active',
      instantBooking:  !doc.requiresApproval,
    },
    locationDetails: {
      currentZone:     doc.zoneCenterName?.trim() || 'Main Zone',
      currentBranch:   doc.zoneCenterName?.trim() || 'Main Branch',
      parkingLocation: '',
      gps: doc.locationGeo?.coordinates
        ? { lng: doc.locationGeo.coordinates[0], lat: doc.locationGeo.coordinates[1] }
        : {},
    },
    documents: {
      rcUrl:         '',
      insuranceUrl:  '',
      pucUrl:        '',
      fitnessUrl:    '',
    },
    images: {
      front:    doc.vehicleImages?.[0] || '',
      back:     doc.vehicleImages?.[1] || '',
      left:     doc.vehicleImages?.[2] || '',
      right:    doc.vehicleImages?.[3] || '',
      interior: '',
      document: '',
      other:    '',
    },
    availability:       mapAvailability(doc.status, doc.availability),
    maintenanceRecords: [],
    auditLogs:          [],
    assignedWorker:     'Unassigned',
  };
}

// ── Run ───────────────────────────────────────────────────────────────────────
async function run() {
  const jsonPath = path.resolve('../onlinestore.vehicles.json');

  console.log('📂 Reading:', jsonPath);
  if (!fs.existsSync(jsonPath)) {
    console.error('❌ File not found:', jsonPath);
    process.exit(1);
  }

  const raw  = fs.readFileSync(jsonPath, 'utf8');
  const docs = JSON.parse(raw);
  console.log(`📋 Total records in JSON: ${docs.length}`);

  console.log('\n🔌 Connecting to MongoDB Atlas...');
  await mongoose.connect(MONGODB_URI);
  console.log('✅ Connected! DB:', mongoose.connection.name, '| Host:', mongoose.connection.host);

  let inserted = 0, skipped = 0, failed = 0;

  for (const doc of docs) {
    const regNo = doc.vehicleNo;
    if (!regNo) {
      console.warn(`  ⚠️  Skipping "${doc.name}" — no vehicleNo`);
      skipped++;
      continue;
    }

    // Check duplicate by regNumber
    const exists = await Vehicle.findOne({ regNumber: regNo });
    if (exists) {
      console.log(`  ⏭️  Already exists: ${regNo} (${doc.name}) — skipping`);
      skipped++;
      continue;
    }

    try {
      const vehicleData = convertVehicle(doc);
      const vehicle = new Vehicle(vehicleData);
      await vehicle.save();
      console.log(`  ✅ ${vehicle.vehicleId} — ${vehicle.name} (${vehicle.regNumber}) [${vehicle.locationDetails.currentZone}]`);
      inserted++;
    } catch (err) {
      console.error(`  ❌ Failed: ${doc.name} (${regNo}) — ${err.message}`);
      failed++;
    }
  }

  const total = await Vehicle.countDocuments();
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`🎉 Import complete!`);
  console.log(`   ✅ Inserted : ${inserted}`);
  console.log(`   ⏭️  Skipped  : ${skipped}`);
  console.log(`   ❌ Failed   : ${failed}`);
  console.log(`   🚗 Total in DB : ${total}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  await mongoose.disconnect();
  console.log('🔌 Disconnected.');
}

run().catch(err => {
  console.error('❌ Fatal:', err.message);
  process.exit(1);
});
